server {
	listen 80;
	server_name localhost;

	root /var/www/html/frontend/dist;
	index index.php index.html;

	location ~* /vendor/ {
		deny all;
		return 403;
	}

	location /api/ {
		try_files $uri $uri/ /api/public/index.php?$query_string;
	}

	location ~ ^/api/public/index\.php$ {
		include fastcgi_params;
		fastcgi_pass php:9000;
		fastcgi_index index.php;
		fastcgi_param SCRIPT_FILENAME /var/www/html/api/public/index.php;
		fastcgi_param SCRIPT_NAME /api/public/index.php;
	}

	location / {
		try_files $uri $uri/ /index.html;
	}

	location ~ \.php$ {
		return 404;
	}

	location ~ /\.ht {
		deny all;
	}
}
